### PR TITLE
AT_041.002 | Header > User > My API keys > Verify that user can navigate to api keys page and see alert info message

### PR DESCRIPTION
**Pull request by shabaiev**
…up fixture file

https://trello.com/c/1rJE3HLe/601-at041002-header-user-my-api-keys-verify-that-user-can-navigate-to-api-keys-page-and-see-alert-info-message

### CODE REVIEW

**Review by alena-resh — DISMISSED** [review]

**Comment by shabaiev** [comment]
@MariaMoroz thank you kindly :) 

@MarinaMone yeah - copypasted name from the wrong ticket, good catch

**Review by Bannikova77 — COMMENTED** [review]
Please put the ; after the steps, all the testcases in our group are wIth ; sign after each step

**Review by Bannikova77 — APPROVED** [review]
good job!

**Review by LIliia149 — DISMISSED** [review]
Good job!

**Review by LIliia149 — APPROVED** [review]
Approved

**Review by SvetlanaG1011 — DISMISSED** [review]

**Review by adiuzhikov — APPROVED** [review]
Approved

**Review by LIliia149 — APPROVED** [review]
Good

**Pull request merged**
