### PR TITLE
AT_013.002 | NavBar > After redirecting to the Blog page 10 posts are displayed on the first page

### PR DESCRIPTION
**Pull request by adiuzhikov**
https://trello.com/c/ROuIICE6/84-at013002-navbar-after-redirecting-to-the-blog-page-10-posts-are-displayed-on-the-first-page

### CODE REVIEW

**Review by Alzhan-B — APPROVED** [review]
looks ok

**Review by shabaiev — APPROVED** [review]
LGTM

**Review by Ekaterina-Bondareva — APPROVED** [review]

**Review by SvetlanaKanel — APPROVED** [review]

**Review by oxangyal — APPROVED** [review]

**Review by Bannikova77 — APPROVED** [review]

**Review by JulieBorisova — APPROVED** [review]
approved

**Comment by engineeryulia** [comment]
Approved

**Review by derearte — APPROVED** [review]
Approved

**Pull request merged**
