### PR TITLE
AT_010.004 | Marketplace > Verify all orange links on the page

### PR DESCRIPTION
**Pull request by StanislavBliss**
https://trello.com/c/kjgW7jcO/121-tc010004-marketplace-verify-all-orange-links-on-the-page

### CODE REVIEW

**Review by MarinaMone — CHANGES_REQUESTED** [review]
This is looking good

**Review by Achillcm — APPROVED** [review]

**Review by MarinaMone — APPROVED** [review]

**Review by Achillcm — APPROVED** [review]
Approved

**Review by Achillcm — APPROVED** [review]

**Review by MarinaMone — APPROVED** [review]
Looking good

**Review by qa-tester22 — APPROVED** [review]
ok

**Comment by qa-tester22** [comment]
ok

**Review by qa-tester22 — APPROVED** [review]

**Review by Achillcm — APPROVED** [review]

**Review by qa-tester22 — APPROVED** [review]

**Review by kgoldpasv — COMMENTED** [review]
looks good , approved

**Review by kgoldpasv — APPROVED** [review]

**Review by ElviraAvshalumov — APPROVED** [review]

**Pull request merged**
