### PR TITLE
AT_050.002 | Footer > Verify that user can be redirected to the 'Term…

### PR DESCRIPTION
**Pull request by shabaiev**
…s and conditions of sale' page. 

https://trello.com/c/SkdtXGbl/281-tc050002-footer-verify-that-user-can-be-redirected-to-the-terms-and-conditions-page

### CODE REVIEW

**Review by SvetlanaKanel — DISMISSED** [review]
Good job!

**Review by TimothyHuxx — CHANGES_REQUESTED** [review]
Please DO NOT make any changes to config files.

**Comment by shabaiev** [comment]
@TimothyHuxx  fixed

**Review by SvetlanaKanel — APPROVED** [review]
good job!

**Review by TimothyHuxx — APPROVED** [review]
Approved

**Pull request merged**
