### PR TITLE
AT_012.001 | Partners > CMS > Verifying 4 buttons exist in the section

### PR DESCRIPTION
**Pull request by Ekaterina-Bondareva**
https://trello.com/c/5iJyLH3Q/252-at012001-partners-cms-verifying-4-buttons-exist-in-the-section

### CODE REVIEW

**Review by AnnaIurchyk — APPROVED** [review]
Approved

**Comment by engineeryulia** [comment]
Aproved

**Review by oxangyal — APPROVED** [review]
approved

**Review by engineeryulia — APPROVED** [review]
LGFM

**Pull request merged**
