### PR TITLE
RF | AT_038.001 | POM _ redirects for business page

### PR DESCRIPTION
**Pull request by engineeryulia**
https://trello.com/c/wzE2gwHU/777-rf-at038001-pom-redirects-for-business-pag

### CODE REVIEW

**Review by Rom-T — APPROVED** [review]

**Comment by Rom-T** [comment]
why is more than 1 test refactored in one PR

**Comment by engineeryulia** [comment]
I can see that  my other branch PR-400 is pulling up I’m not figuring out
what’s going on

**Comment by engineeryulia** [comment]
Do you know how can I split them?

**Review by LIliia149 — APPROVED** [review]
lgtm

**Pull request merged**
