### PR TITLE
API | andreyLapinSpec

### PR DESCRIPTION
**Pull request by mznyerz**

### CODE REVIEW

**Review by Massik78 — APPROVED** [review]

**Review by nat-belyaeva — DISMISSED** [review]

**Review by nat-belyaeva — APPROVED** [review]

**Review by OLgaByR — COMMENTED** [review]
lines 107 -111 are commented,  is it supposed to be like this?

**Comment by mznyerz** [comment]
> lines 107 -111 are commented, is it supposed to be like this?
Yes. I will add tests to the file starting from line 107.
Commented so as not to forget (:

**Comment by mznyerz** [comment]
Yes. I will add tests to the file starting from line 107.
Commented so as not to forget (:

**Review by nat-belyaeva — APPROVED** [review]

**Comment by OLgaByR** [comment]
> Yes. I will add tests to the file starting from line 107.
> Commented so as not to forget (:

Ok, just to make sure)

**Pull request merged**
