### PR TITLE
RF | questionsPageSpec > AT_015.001 add method

### PR DESCRIPTION
**Pull request by TimothyHuxx**
https://trello.com/c/MucmWfeY/868-rf-questionspagespec-at015001-add-method

### CODE REVIEW

**Comment by TimothyHuxx** [comment]
[RF | questionsPageSpec > AT_015.001 add method](https://trello.com/c/MucmWfeY/868-rf-questionspagespec-at015001-add-method)

**Comment by TimothyHuxx** [comment]
[RF | questionsPageSpec > AT_015.001 add method](https://trello.com/c/MucmWfeY/868-rf-questionspagespec-at015001-add-method)

**Review by engineeryulia — APPROVED** [review]
LGFM

**Review by Alzhan-B — APPROVED** [review]
LGTM

**Pull request merged**
