### PR TITLE
AT_028.001 | Footer > About us > Verify "About us" link redirects to the corresponding page

### PR DESCRIPTION
**Pull request by lordlor444**
modify_test_28_ add_new_lines

### CODE REVIEW

**Comment by Sana291** [comment]
hey, your branch doesnt have proper name you may want to change ticket number and have name same as ticket for AT

**Comment by lordlor444** [comment]
It was updated accordingly. Thank you!

**Review by Sana291 — APPROVED** [review]

**Review by elviraKh1 — COMMENTED** [review]
Hi, I don't see link to trello AT

**Comment by lordlor444** [comment]
https://trello.com/c/E2tZPFYM/86-at028001-footer-about-us-verify-about-us-link-redirects-to-the-corresponding-page

**Review by teachandlearn999 — APPROVED** [review]

**Pull request merged**
