### PR TITLE
AT_055.001 | Main-page > Our-new-product > Solar-Radiation-API

### PR DESCRIPTION
**Pull request by Anakondos**
https://trello.com/c/foUYsV8U/759-at055001-main-page-our-new-product-solar-radiation-api

### CODE REVIEW

**Comment by Anakondos** [comment]
https://trello.com/c/foUYsV8U/759-at055001-main-page-our-new-product-solar-radiation-api

**Comment by Anakondos** [comment]
[AT_055.001 | Main page > Our new product > Solar Radiation API](https://trello.com/c/foUYsV8U/759-at055001-main-page-our-new-product-solar-radiation-api)

**Review by Anakondos — COMMENTED** [review]
merge

**Review by Anakondos — COMMENTED** [review]
complete merge of changes

**Review by Lizzzzi — CHANGES_REQUESTED** [review]
it seems very strange to me, these two empty files in the root of the project (-Our-new-product-  and -Solar-Radiation-API)
Are they really needed?

**Comment by SergeiKuznetsov** [comment]
Переименуйте ветку и отправьте заново.
Не используйте в названии служебные символы `><|`

**Comment by SergeiKuznetsov** [comment]
Потом сделате 
image
и продолжите работу

**Comment by Anakondos** [comment]
Сергей, Спасибо большое!

**Pull request closed without merging**
