### PR TITLE
RF/jScript_group_AC_025_006

### PR DESCRIPTION
**Pull request by Vik1975**
AC_025_006 refactored

### CODE REVIEW

**Comment by EkaterinaRomankova** [comment]
You forgot remove "only"

**Comment by Vik1975** [comment]
Ooops

**Review by OlgaAutomation4 — DISMISSED** [review]

**Comment by Vik1975** [comment]
Thank you @EkaterinaRomankova. Fixed

**Review by SvetlanaKanel — APPROVED** [review]
good job!

**Review by EkaterinaRomankova — APPROVED** [review]

**Comment by Vik1975** [comment]
@SvetlanaKanel Thank you

**Comment by Vik1975** [comment]
@EkaterinaRomankova Thank you

**Comment by Vik1975** [comment]
https://trello.com/c/xFobZHHz/139-at025006-main-menu-dashboard-verify-the-first-button-contact-us-is-clickable-and-redirect-user-to-new-url-questions

**Review by MariaMoroz — CHANGES_REQUESTED** [review]
Не нашла карточку рефакторинга RF

**Comment by Vik1975** [comment]
Я не вроде прикрепил. Но только не вначале. Забыл вначале

**Comment by MariaMoroz** [comment]
прикрепленная карточка к пиару - это не карточка рефакторинга

**Comment by Vik1975** [comment]
@MariaMoroz Unable to create new RF card from template. "Something went wrong" error message appears.

**Comment by Vik1975** [comment]
https://trello.com/c/TmhArQk4/657-rf-jscriptgroup-at025006-main-menu-dashboard-verify-the-first-button-contact-us-is-clickable-and-redirect-user-to-new-url-questi

**Comment by Vik1975** [comment]
@MariaMoroz . RF card linked.

**Review by MariaMoroz — APPROVED** [review]

**Comment by Vik1975** [comment]
@MariaMoroz Thank you

**Pull request merged**
