### PR TITLE
AT_012.007 | Partners > CMS > Verification the number of Buttons

### PR DESCRIPTION
**Pull request by Anakondos**

### CODE REVIEW

**Comment by Anakondos** [comment]
https://trello.com/c/Ir5PFvNV/396-at012007-partners-cms-verification-the-number-of-buttons

**Comment by Anakondos** [comment]
[AT_012.007 | Partners > CMS > verification the number of Buttons](https://trello.com/c/Ir5PFvNV/396-at012007-partners-cms-verification-the-number-of-buttons)

**Review by SvetlanaKanel — APPROVED** [review]
good job!

**Review by LIliia149 — APPROVED** [review]
Approved

**Pull request merged**
